"""initial schema

Revision ID: adb13cebb0b0
Revises: 
Create Date: 2026-09-24 20:50:33.562965

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import apollo.db.types

# revision identifiers, used by Alembic.
revision: str = 'adb13cebb0b0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('friction', sa.Text(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('wins', sa.JSON(), nullable=False),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.create_index('ix_checkins_kind_ref', ['kind', 'ref_id', 'occurred_at'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('processed_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index('ix_events_unprocessed', ['processed_at', 'id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_after', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'run_after', 'priority', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body_path', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body_path')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('sent_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_id', 'period', name='uq_notification_idempotency')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_pending', ['status', 'scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('expires_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('decided_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index('ix_pending_status', ['status', 'created_at'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadence', sa.String(length=32), nullable=False),
    sa.Column('period_start', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('period_end', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('completed_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadence', 'period_start', name='uq_review_period')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_logs_run_id'), ['run_id'], unique=False)

    op.create_table('schedule_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('predicate', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_policy', sa.String(length=32), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('horizon_start', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('horizon_end', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('cadence', sa.String(length=64), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cadence', sa.String(length=200), nullable=True),
    sa.Column('policy', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_cadence', sa.String(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('rrule', sa.String(length=400), nullable=False),
    sa.Column('target_per_period', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_done_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('done_when', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('energy', sa.String(length=32), nullable=True),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', apollo.db.types.UTCDateTime(length=32), nullable=True),
    sa.Column('created_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.Column('updated_at', apollo.db.types.UTCDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_status_due', ['status', 'due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_status_due')

    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('habits')
    op.drop_table('practices')
    op.drop_table('metrics')
    op.drop_table('goals')
    op.drop_table('settings')
    op.drop_table('schedule_rules')
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_logs_run_id'))

    op.drop_table('run_logs')
    op.drop_table('reviews')
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_status')

    op.drop_table('pending_actions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index('ix_notifications_pending')

    op.drop_table('notifications')
    op.drop_table('journal_entries')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_unprocessed')
        batch_op.drop_index(batch_op.f('ix_events_type'))

    op.drop_table('events')
    op.drop_table('conversations')
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_index('ix_checkins_kind_ref')

    op.drop_table('check_ins')
    op.drop_table('audit_log')
    op.drop_table('areas')
    # ### end Alembic commands ###
